# Site settings
author: Lés. 
title: Lés Blogged More.
header-img: img/home-bg.png
email: lesosorio17@gmail.com
copyright_name: Lés. 
description: > # this means to ignore newlines until "baseurl:"
  Making Lés More A Day at A Time. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LesOsorio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
